### PR TITLE
Fix bugs surrounding gene adding

### LINKED ISSUE #866: “Bulk add genes” should recognize lowercase inputs
“Bulk add genes” doesn’t recognize lowercase, but “Autosuggest genes” does. We shoul make it consistent, and in favor of the more inclusive experience: “Bulk add genes” should recognize lowercase inputs.
Bulk add genes  doesn't recognize lowercase inputs, but  Autosuggest genes  does

### PR DESCRIPTION
**Pull request by seve**
This PR fixes the following bugs:
* The add button not properly working on `Autosuggest gene`
* `bulk add genes` working case-sensitively

---
Changes:
* `geneExpression` component
   * Add onClick listener to `Add gene` button
   * Refactored `handleBulkAddClick()` to be case-insensitive 

---
closes #866

### CODE REVIEW

File: client/src/components/geneExpression/index.js [hunk 1]
```diff
@@ -108,7 +130,7 @@ class GeneExpression extends React.Component {
   handleClick(g) {
     const { world, dispatch, userDefinedGenes } = this.props;
     const varIndexName = world.schema.annotations.var.index;
-    const gene = g.target;
+    const gene = g?.target;
```
Comment (bkmartinjr) [inline client/src/components/geneExpression/index.js]: this would be much better replaced with a more expliict action, such as:

```
if (!g) return;
```

File: client/src/components/geneExpression/index.js [hunk 2]
```diff
@@ -138,27 +160,43 @@ class GeneExpression extends React.Component {
...
-          }
-          return dispatch(actions.requestUserDefinedGene(gene));
-        })
-      ).then(
+
+      const promises = [];
+      for (let i = 0, { length } = upperGenes; i < length; i += 1) {
+        const upperGene = upperGenes[i];
+
+        if (genes.length === 0) {
```
Comment (bkmartinjr) [inline client/src/components/geneExpression/index.js]: this should not be in the loop - it is a constant every time.   But by putting it in the loop, this necessary check is omitted.   Move outside the loop, eg, immeiately after the `genes` variable is set (line 165).

File: client/src/components/geneExpression/index.js [hunk 3]
```diff
@@ -138,27 +160,43 @@ class GeneExpression extends React.Component {
...
+          /* Because of _.pull() this case is unreachable */
+          return keepAroundErrorToast("Must enter a gene name.");
+        }
+        if (upperUserDefinedGenes.indexOf(upperGene) !== -1) {
+          return keepAroundErrorToast("That gene already exists");
+        }
+
+        const indexOfGene = upperWorldGenes.get(upperGene);
+
+        if (indexOfGene) {
```
Comment (bkmartinjr) [inline client/src/components/geneExpression/index.js]: this logic is inverted - don't you mean `if (!indexOfGene)`?

File: client/src/components/geneExpression/index.js [hunk 4]
```diff
@@ -73,6 +75,26 @@ class GeneExpression extends React.Component {
     };
   }
 
+  _genesToUpper = col => {
+    // Has to be a Map to preserve index
+    let listGenes = col;
+
+    // Extract the array from column if applicable
+    if (typeof col.asArray === "function") {
```
Comment (bkmartinjr) [inline client/src/components/geneExpression/index.js]: recommend deleting this polymorphic arg support, and just make this function _require_ an array as an argument.  Much simpler conceptually.

File: client/src/components/geneExpression/index.js [hunk 5]
```diff
@@ -138,27 +160,43 @@ class GeneExpression extends React.Component {
...
-            return keepAroundErrorToast(
-              `${gene} doesn't appear to be a valid gene name.`
-            );
-          }
-          return dispatch(actions.requestUserDefinedGene(gene));
-        })
-      ).then(
+
+      const promises = [];
+      for (let i = 0, { length } = upperGenes; i < length; i += 1) {
```
Comment (bkmartinjr) [inline client/src/components/geneExpression/index.js]: this is not as clear as the original code which used `.map()`.   Why not simply do `upperGenes.map()`?

File: client/src/components/geneExpression/index.js [hunk 6]
```diff
@@ -234,6 +272,7 @@ class GeneExpression extends React.Component {
                   return "";
                 }}
                 itemListPredicate={filterGenes}
+                onActiveItemChange={item => this.setState({ activeItem: item })}
```
Comment (bkmartinjr) [inline client/src/components/geneExpression/index.js]: best practice to set default state

File: client/src/components/geneExpression/index.js (hunk 5 above)
Comment (seve) [reply client/src/components/geneExpression/index.js]: upperGenes is a Map so had to pull an array out from keys using [...map.keys()]
