### PR TITLE
brushable histogram brush selection responds to state updates

### LINKED ISSUE #627: Reset does not clear histogram selection brush
If you do a Reset (via Reset button), selection brushes on histograms are not cleared.

To reproduce:
1. load a dataset, eg, pbmc3k
2. brush select a section of any continuous metadata (eg, 'n_genes' in pbmc3k)
3. click Reset button

the entire UI, except for the histogram brush, is reset.   The brush should be cleared.

Update: this same underlying bug affects Undo/Redo.

### PR DESCRIPTION
**Pull request by bkmartinjr**
Fixes #627 

The brushable histogram selection "brush" was not integrated with redux state, and would therefore not correctly clear on an undo or reset.

This change includes:
* add a `continousSelection` reducer and state to hold the brushable histogram state
* HistogramBrush component now responds to state changes by removing or moving its brush

### CODE REVIEW

File: client/src/reducers/continuousSelection.js [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+    }
+    case "continuous metadata histogram start":
+    case "continuous metadata histogram brush":
+    case "continuous metadata histogram end": {
+      const name = makeContinuousDimensionName(
+        action.continuousNamespace,
+        action.selection
+      );
+      const continuousSelection = { ...state };
+      continuousSelection[name] = action.range;
```
Comment (csweaver) [inline client/src/reducers/continuousSelection.js]: You could use computed property names `computed key` to keep the state return statement in the usual fashion:
```
const continuousSelection = { ...state, [name]: action.range };
```

File: client/src/reducers/index.js [hunk 2]
```diff
@@ -63,6 +64,7 @@ const Reducer = undoable(
     ["universe", universe],
     ["world", world],
     ["categoricalSelection", categoricalSelection],
+    ["continuousSelection", continuousSelection],
```
Comment (csweaver) [inline client/src/reducers/index.js]: This data structure seems like it could be simplified since the strings and variables are always the same.

File: client/src/components/brushableHistogram/index.js [hunk 3]
```diff
@@ -86,19 +87,51 @@ class HistogramBrush extends React.Component {
...
+      const { isObs, isUserDefined, isDiffExp } = this.props;
+      const myName = makeContinuousDimensionName(
+        { isObs, isUserDefined, isDiffExp },
+        field
+      );
+      const range = continuousSelection[myName];
+      const { brushXselection, brushX } = this.state;
+      if (brushXselection) {
+        const selection = d3.brushSelection(brushXselection.node());
+        if (!range && selection) {
```
Comment (csweaver) [inline client/src/components/brushableHistogram/index.js]: Suggest commenting the conditions. What are the scenarios that each get called? I'm having trouble figuring that out.

File: client/src/reducers/continuousSelection.js (hunk 1 above)
Comment (bkmartinjr) [reply client/src/reducers/continuousSelection.js]: will fix

File: client/src/reducers/index.js (hunk 2 above)
Comment (bkmartinjr) [reply client/src/reducers/index.js]: could you suggest something concrete?   I don't think we can assume that the functions and fields have the same name, but they often will, and I'm open to improving this.  I just couldn't come up with a concrete idea!

File: client/src/components/brushableHistogram/index.js (hunk 3 above)
Comment (bkmartinjr) [reply client/src/components/brushableHistogram/index.js]: comments added - please review.

Comment (csweaver) [reply client/src/components/brushableHistogram/index.js]: much better 👍

File: client/src/reducers/index.js (hunk 2 above)
Comment (csweaver) [reply client/src/reducers/index.js]: I'm thinking on it. This should block the merge.
