### PR TITLE
undo/redo cleanup

### LINKED ISSUE #1099: erratic undo/redo/reset behavior on "color by" toggling
Here is an example of one instance where history is lost and it isn't possible to undo or redo:
bug1

Here is another example where undoing and redoing do not have an effect on the color state:
bug2

### LINKED ISSUE #1153: Annotations have unpredictable undo/redo behavior
### Expected
Expected steps:
1. Delete a category
1. Undo button is active (indicates last action is undoable)
1. Click Undo

Expected results:
* Category is restored

### Current
Steps to reproduce bug:
1. Start from a refreshed page
1. Delete a category

Results:
* ~~Undo button is not active~~
* Category is restored

### Expected
Expected steps:
1. Hover on category options
1. Hover on options of a label
1. Edit label name
1. Submit change
1. Undo button is active (indicates last action is undoable)
1. Click undo

Expected results:
* No edit dialog
* Label is renamed

### Current
Steps to reproduce bug:
1. Hover on category options
1. Hover on options of a label
1. Edit label name
1. Submit change
1. Undo button is active (indicates last action is undoable)
1. Click undo

Results:
* Edit label dialog opens with label name from before edit

### Expected
Expected steps:
1. Hover on category options
1. Add a label
1. Submit label name
1. Undo button is active (indicates last action is undoable)
1. Click undo

Expected results:
* Label is removed
* No new label dialog
* Is redoable

### Current
Steps to reproduce bug:
1. Hover on category options
1. Add a label
1. Submit label name
1. Undo button is active (indicates last action is undoable)
1. Click undo

Results:
* Label is removed
* New label dialog opens
* Is not redoable

### PR DESCRIPTION
**Pull request by bkmartinjr**
Fixing various undo/redo issues:
* color-by was set to dedup, even though we long ago switched it to a toggling UI.  Removed the dedup.  Fixes #1099 and reverts #1124 which introduced several other issues.
* refactored various user annotation actions to be history-management-friendly (thereby making undo/redo work with category/label editing).  In particular, there were many actions which *both* controlled dialog modes and committed state to the store - these are now split, enabling proper history management.
* moved autosave state out of undoable-managed state (it should never have been in it)
* added many missing action types to the undoable config
* add missing preventDefaults on form submission for annotations, which fixed a number of react errors showing on console.
* cancelling out of various dialogs (eg edit label) and then opening the dialog again would incorrectly manage the initial input widget state (it displayed the old, cancelled edit text)

Fixes #1153

### CODE REVIEW

File: client/src/reducers/undoableConfig.js [hunk 1]
```diff
@@ -229,7 +240,7 @@ function shallowArrayEq(arrA, arrB) {
 }
 
 /* configuration for the undoable meta reducer */
-const debug = false; // set truish for undoble debugging
+const debug = false; // set truish for undoble debugging. Higher number is more verbose.
```
Comment (colinmegill) [inline client/src/reducers/undoableConfig.js]: Comment does not reflect line of code

Comment (bkmartinjr) [reply client/src/reducers/undoableConfig.js]: sure it does!  but I'll make it even more obvious :-)
