### PR TITLE
Cluster Occupancy (n dim cube)

### LINKED ISSUE #462: n-dim summary cube
On startup and subset to current selection, summarize how categorical metadata is broken down by other categorical metadata, add the results of that calculation to world in the following format:

image

Use case:

image

### PR DESCRIPTION
**Pull request by colinmegill**
image

Fixes #462

### CODE REVIEW

File: client/src/components/categorical/value.js [hunk 1]
```diff
@@ -52,13 +57,22 @@ class CategoryValue extends React.Component {
     /* this is the color scale, so add swatches below */
     const c = metadataField === colorAccessor;
```
Comment (bkmartinjr) [inline client/src/components/categorical/value.js]: variable name could be more descriptive

File: client/src/components/categorical/occupancy.js [hunk 2]
```diff
@@ -0,0 +1,88 @@
...
+    //   stack.push({
+    //     key,
+    //     value,
+    //     rectWidth: scaledValue,
+    //     offset: currentOffset,
+    //     fill: colorScale(categories.indexOf(key))
+    //   });
+    //   currentOffset += scaledValue;
+    // });
+
```
[the remark this answers is not in the document]
Comment (bkmartinjr) [reply client/src/components/categorical/occupancy.js]: I agree!

File: client/src/components/categorical/occupancy.js [hunk 3]
```diff
@@ -0,0 +1,85 @@
...
+    return (
+      <svg
+        style={{
+          marginRight: 5,
+          width,
+          height
+        }}
+      >
+        {_.map(stack, d => (
```
Comment (bkmartinjr) [inline client/src/components/categorical/occupancy.js]: I like the fact that you are no longer using lodash as much (eg, above array.forEach()).   Why not use the built-in map as well?

File: client/src/components/categorical/occupancy.js [hunk 4]
```diff
@@ -0,0 +1,85 @@
...
+    //     rectWidth: scaledValue,
+    //     offset: currentOffset,
+    //     fill: colorScale(categories.indexOf(key))
+    //   });
+    //   currentOffset += scaledValue;
+    // });
+
+    const cat = categoricalSelectionState[colorAccessor];
+
+    cat.categoryValues.forEach(d => {
```
Comment (bkmartinjr) [inline client/src/components/categorical/occupancy.js]: this could be rewritten as `cat.categoryValues.map(...)`, and get rid of the manual stack.push().  Style comment only, so at your discretion.  I tend to prefer map() when that is the only side effect.
